name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 0点执行
  workflow_dispatch: # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: mtvpls/MoonTVPlus
          upstream_checkout_branch: main
          target_checkout_branch: main
          upstream_pull_args: '-s recursive -X theirs'
